# The coco2017 dataset with instance, stuff and caption annotations.
_target_: ocl.datasets.WebdatasetDataModule
train_shards: "${oc.env:DATASET_PREFIX}/movi_e/train_with_label/shard-{000000..000290}.tar"
train_size: 84831
val_shards: "${oc.env:DATASET_PREFIX}/movi_e/val/shard-{000000..000025}.tar"
val_size: 6000
use_autopadding: true
